### ISSUE TITLE
Create test spring boot project for Timur

### ISSUE THREAD

**Issue by kostua16** [kostua16/nc_train_project_group6_2019#1]
Инструкции 
https://docs.google.com/document/d/1DyaSjvpENSzDNJfWj2kRF35K63n1TbkdtOgspqEVSgg/edit 

Задача:
Написать простое Web приложение, которое имеет 1 rest сервис, по адресу /test/test,
и возвращает текущую дату.

**Comment by Timurka169** [comment]
[springapp1.zip](https://github.com/kostua16/nc_train_project_group6_2019/files/3931502/springapp1.zip)
